version: 2.1

description: >
  Split circle configuration across monorepo packages and skip jobs for packages that did not change

executors:
  circletron-executor:
    docker:
      - image: ghcr.io/empathycom/circletron:3.0.15

jobs:
  trigger-jobs:
    executor: circletron-executor
    environment:
      CIRCLETRON_PIPELINE_ID: '<< pipeline.id >>'
      CIRCLETRON_PIPELINE_NUMBER: '<< pipeline.number >>'
    steps:
      - checkout
      - run:
          name: trigger jobs
          command: circletron
      - store_artifacts:
          path: /tmp/circletron/skips.json
          destination: circletron/skips.json
